language: python
python:
- '3.6'
script:
- python setup.py install
deploy:
  provider: pypi
  user: sepulword
  on:
    branch: master
  password:
    secure: RfuHhWP/nbvt3Fn/VvztaVbkQtISGlIZ7hPMwhpAXNsGVYLOIWZlAezE0t0vtU9jOvPUyb3DCE1iFO3yubV6rNtSxaDDhDnOPtmDi2/9jEWuuUoN7OWXVMyHcgd0CrYm2bRj1gVLa/e+F8D9l7HE4sibML72gqiW+peDA03eLuzmnoXr0JRy7/QA3P7hjxvAiXci1oo1ZTHKaLAjjgZXD15E5emf1si+RkUyARhwRmEa4aNL7G1QelEcMDk1aNpz1X+UdLVs0ILQfQoekfZT16oC+0VSvLvx6kkiTWWlgfK3XjR2XOqXi76MVjXYpdptX7VRnPNyK3CFZZ4EZCBjl1tD9PD6t7pAwiKQdfNYX2/kjq88NFrLaO7aKoarJptLROCXqSGJOC6XTOpzg67IwaV19LTLPDAbbV3nxaHRoQQyEv1fwcrJV/DRlHEsmOxBagCCkHduCeMR6Yf9M/tK3nkpjULKIkDfUm8dOFwMb4TINFZiBVBFNsQ+cMSc/bJuWEVKNARLSTh3690P/rZSW2SIIvJwwdHpuzfKTE3efVEjl8EMNS5Z7qh+1T+UMG3iXITWdQnyMLv9GLf3Reux0i+wW8Ngn5RdTiO8xEp6TyhvOy4BDdtBFlTmEuOSSKDSO/I3ys/jthSzTNxkmQk7H7aySdqtBO/tjnd7fyrmcwc=
