language: python
python:
- '3.6'
script:
- python setup.py install
deploy:
  provider: pypi
  user: sepulword
  on:
    branch: master
  password:
    secure: N3dFojohL8Ur/SlMOaPdp7qHRyLWvwpxmx85tlIZ1Gp+98CR9ptKIHEuCNwu9m+yvlWbWD6sKQNsp7t8aG4a5bRdqrFrEENIBAQ3GTGmXMY9IDZVaJccjNo0di5eK+xlrHZOIYY2l1sqtUqZ3YbkREERe9CFr8v1nlI8X9UvgdS83IZ4eSgjH3pN7PzN7pr0hp9Y4/W1xUaz10gHwCVZGvMdI0oIFgjSmBL3u5TEUZFn5zovsPw1nTVxanpkOtBGVRiRN8VETBh2PO+rNpUG/DnDN1BTz9neHPOCcKV1pXnANMxwaus4APSPf6jp5IL56Lx/O2whn+NDLZNRNRt1nOd7QVzFz41PX3WDDlmqYo5+14IlodQcgH5jaUZfVwusqMJRDgLKWa5ALCRevHgTfClNQfxghO/XedxwgUHs3fPN+bqe5b/aXmhj+ZJ+tBGu0jzibTa4gACq0dINgY2rHu+T3Chqp6MNItM+MO5fMEX/o335J0tNXwdTBUD424tucNwhAEamMky4EWgtx8cp+PYvO4Jc7V0E8QVaFZFaSXjL7CJnZaMr6cOspszADmSOj3S16ty8wD+ItQks/HfSD1+03Y0OzzuclkmvYGBSHzDIBqrB/ApiHkJRh9WOTe9RHRSQTnzl7mAsfMH7skeLZPh7EK2P4gL09ne6SzbmXYo=
