language: python
python:
- '3.6'
script:
- python setup.py install
deploy:
  provider: pypi
  user: sepulword
  on:
    branch: master
  password:
    secure: RjPkWcr0MnCgirsbYRxrX+Ini/uNfvlJT5Hr8kwsELBJMYEAxuSFVDPohJW/TL0a1F7cFK3C475mzfHKGElgyXouq/P2s5GJAGzzb+w40JblTLhmkWJq4KQ5FuM42vy+grkPQiPW7iL8FeQewxF4JDN/KZ3sxjsDXKJz+L+Br6TSdTKmQAw3q2T+4qph7fX5bd5AhIFuJiXjzHiDTOyg/iWwSySJgKXq1BY/GlFwLeGOGRsevR1WC7TDFMeOcDKgHtUlpTQWu9n1Gz8MqPxffGTIlDEGbjmLkQXdq0j9mlDsPh4KxMfI9muE2bCX6fCDaZl7fNeQWe8gnjd2Z6YfoKUa4xjjvNO7RraadbqUEZrubkDeEIuAf1FqByMORH2j3X2FVgg5LAFD/I5DIr7EsYUa75zAblauWdylrhe+AxIx1wBDMUWR9BP3yPUw/oUaW3QZ3MzUk/oBp/nBTeL1jvQeVgMMmpsSYM5+P2h0pFao8A+jIYEbLjdykelMkeuFAL5EKUCDYyWAtHM3QQs1xZi7ztHOqwEGasdmyBU2QlU3tfLnnqzJ0udkvZdzGK50NJ0W+p4gFkZGtC057p8VfP3nvBTfeN43HCAH9AoNS/Tjn+pyqKYYM57SY7nm7WpthVy1dTHyaGvk6q4iR62CegwzGmPCQB2S9uLHzjVbnh0=
